// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sunnah-redesign/Current.tsx": () => import("../components/mockups/sunnah-redesign/Current.tsx"),
  "./components/mockups/sunnah-redesign/GoldenAgeHome.tsx": () => import("../components/mockups/sunnah-redesign/GoldenAgeHome.tsx")
};
